/*
** /boot/develop/own/GUI/Lock/Lock Workstation copy/src_app/resources.h
**
** Automatically generated by BResourceParser on
** Friday, May 03, 2002 at 13:50:52.
**
*/

enum {
	R_JPEG_login_gfx = 1,
	R_JPEG_NoUserImage = 2,
	R_JPEG_UserImage = 3
};
